# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turso < Formula
  desc ""
  homepage "https://github.com/chiselstrike/homebrew-tap"
  version "1.0.6"

  depends_on "libsql/sqld/sqld"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v1.0.6/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "a68957669a274583e294215052fcca226986affd0a1b775bf071d9370a1ba170"

      def install
        bin.install "turso"
        bash_completion.install "completions/turso.bash" => "turso"
        zsh_completion.install "completions/turso.zsh" => "_turso"
        fish_completion.install "completions/turso.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v1.0.6/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "6009a30cdf9bd67282ba6be3a90f1d00a7fc66a3a01359184115f925beeb23dd"

      def install
        bin.install "turso"
        bash_completion.install "completions/turso.bash" => "turso"
        zsh_completion.install "completions/turso.zsh" => "_turso"
        fish_completion.install "completions/turso.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chiselstrike/homebrew-tap/releases/download/v1.0.6/homebrew-tap_Linux_x86_64.tar.gz"
        sha256 "b5c44dd826316ce68497006882dcd6c5bb4d943446296114d8b2e771ee1c5386"

        def install
          bin.install "turso"
          bash_completion.install "completions/turso.bash" => "turso"
          zsh_completion.install "completions/turso.zsh" => "_turso"
          fish_completion.install "completions/turso.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chiselstrike/homebrew-tap/releases/download/v1.0.6/homebrew-tap_Linux_arm64.tar.gz"
        sha256 "62a3bb63d191e4439510744d8b66b545bad4903a6ca7132638e74966da1453bf"

        def install
          bin.install "turso"
          bash_completion.install "completions/turso.bash" => "turso"
          zsh_completion.install "completions/turso.zsh" => "_turso"
          fish_completion.install "completions/turso.fish"
        end
      end
    end
  end

  def post_install
    exec('turso post-install')
  end
end
