# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turso < Formula
  desc ""
  homepage "https://github.com/chiselstrike/homebrew-tap"
  version "0.96.1"

  depends_on "libsql/sqld/sqld"

  on_macos do
    on_intel do
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.96.1/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "32cbda18ca572a276ce7d6f4de8819fca75fcc32710d3bffd74d2e6820ebb4f5"

      def install
        bin.install "turso"
        bash_completion.install "completions/turso.bash" => "turso"
        zsh_completion.install "completions/turso.zsh" => "_turso"
        fish_completion.install "completions/turso.fish"
      end
    end
    on_arm do
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.96.1/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "d72d969941c984c731a8329d84fb67cda16ad31fcd96254d2c127366adfa1c05"

      def install
        bin.install "turso"
        bash_completion.install "completions/turso.bash" => "turso"
        zsh_completion.install "completions/turso.zsh" => "_turso"
        fish_completion.install "completions/turso.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.96.1/homebrew-tap_Linux_x86_64.tar.gz"
        sha256 "8fa42bc9a7647b00c8e43b62b8b501e481a3244105fd3a43546730eded747465"

        def install
          bin.install "turso"
          bash_completion.install "completions/turso.bash" => "turso"
          zsh_completion.install "completions/turso.zsh" => "_turso"
          fish_completion.install "completions/turso.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.96.1/homebrew-tap_Linux_arm64.tar.gz"
        sha256 "aefe7efb2203ddb0da5dd1293d002513be0014b76bbf80cb55f716f0f9ce8bad"

        def install
          bin.install "turso"
          bash_completion.install "completions/turso.bash" => "turso"
          zsh_completion.install "completions/turso.zsh" => "_turso"
          fish_completion.install "completions/turso.fish"
        end
      end
    end
  end

  def post_install
    exec('turso post-install')
  end
end
